/*
 * Copyright (c) 2023, Anlogic Inc. and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __AL_MISC_LL_H_
#define __AL_MISC_LL_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "al_misc_hw.h"

typedef enum
{
    AL_MISC_UDMA         = 0,
    AL_MISC_USART0       = 1,
    AL_MISC_USART1       = 2,
    AL_MISC_I2C          = 3,
    AL_MISC_QSPIXIP0     = 4,
    AL_MISC_QSPI1        = 5,
    AL_MISC_LGPIO        = 6,
    AL_MISC_AHB          = 7,
    AL_MISC_IDU          = 8,
    AL_MISC_IOMUX        = 9,
} AL_MISC_ModulesEnum;


static inline AL_VOID AlMisc_ll_SetReset(AL_MISC_ModulesEnum Module, AL_BOOL Status)
{
    AL_REG32_SET_BIT(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__SUBM_RESET_CTRL0__ADDR, Module, Status);
}

static inline AL_VOID AlMisc_ll_SetClkEn(AL_MISC_ModulesEnum Module, AL_BOOL Status)
{
    AL_REG32_SET_BIT(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__SUBM_CLK_CTRL0__ADDR, Module, Status);
}


static inline AL_VOID AlMisc_ll_SetTestFabClkDiv(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL0_TEST_FAB_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL0_TEST_FAB_CLK_I__TEST_FAB_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL0_TEST_FAB_CLK_I__TEST_FAB_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetAhbClkDiv(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL1_AHB_SLV0_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL1_AHB_SLV0_CLK_I__AHB_SLV0_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL1_AHB_SLV0_CLK_I__AHB_SLV0_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetUdmaDiv(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL2_UDMA0_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL2_UDMA0_CLK_I__UDMA0_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL2_UDMA0_CLK_I__UDMA0_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetUart0Div(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL3_USART0_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL3_USART0_CLK_I__USART0_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL3_USART0_CLK_I__USART0_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetUart1Div(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL4_USART1_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL4_USART1_CLK_I__USART1_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL4_USART1_CLK_I__USART1_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetIicDiv(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL5_I2C0_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL5_I2C0_CLK_I__I2C0_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL5_I2C0_CLK_I__I2C0_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetQspi1Div(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL6_QSPI1_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL6_QSPI1_CLK_I__QSPI1_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL6_QSPI1_CLK_I__QSPI1_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetQspiXip0Div(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL7_QSPI_XIP0_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL7_QSPI_XIP0_CLK_I__QSPI_XIP0_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL7_QSPI_XIP0_CLK_I__QSPI_XIP0_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetLgpioDiv(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL8_LGPIO0_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL8_LGPIO0_CLK_I__LGPIO0_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL8_LGPIO0_CLK_I__LGPIO0_CLK_I_DIV__SIZE, Div);
}

static inline AL_VOID AlMisc_ll_SetIomuxDiv(AL_U32 Div)
{
    AL_REG32_SET_BITS(MISC_CTRL_BASE_ADDR + SOC_MISC_CTRL__CLK_CTRL9_IOMUX_CLK_I__ADDR,
    SOC_MISC_CTRL__CLK_CTRL9_IOMUX_CLK_I__IONUX_CLK_I_DIV__SHIFT,
    SOC_MISC_CTRL__CLK_CTRL9_IOMUX_CLK_I__IONUX_CLK_I_DIV__SIZE, Div);
}




#ifdef __cplusplus
}
#endif

#endif
