#include "soc_plat.h"

/* all data */
/* generated by system automaticlly */

#include "ph1p35_crg.h"
#include "soc_plat.h"
#include "al_misc_ll.h"

void clk_simple_config()
{
	AlMisc_ll_SetClkEn(AL_MISC_USART1, 1);
	AlMisc_ll_SetClkEn(AL_MISC_IOMUX, 1);
	AlMisc_ll_SetClkEn(AL_MISC_IDU, 1);

}

__attribute__((__used__)) void board_init()
{
	clk_simple_config();

	AlMisc_ll_SetReset(AL_MISC_USART1, 0);
	AlMisc_ll_SetReset(AL_MISC_USART1, 1);
}
