/* IDE_PATH       : F:/AnlogicFpga/TD_6.2.1_Engineer_6.2.168.116/bin/td.exe */
/* IDE_VERSION    : Release: 6.2.1 Build: 168116  */
/* HPF_EXPORT_TIME: 2026/09/17 20:54:18 */
/* HPFTool_Version: 2025/07/09 15:19:18 */

#ifndef __AL_SOC_PLAT_H
#define __AL_SOC_PLAT_H

#ifdef __cplusplus
extern "C" {
#endif

#define HPF_VERSION   202501


/* Clock frequency of all peripherals, generated by system automatically. */
#define Hz                                        1
#define MHz                                1000000U
#define MHZ                                1000000U
#define ENABLE                                  1
#define DISABLE                                 0

#define PH1P35_MCU_DPLL_BYPASS              DISABLE
#define PH1P35_MCU_CORE_CLOCK             300000000
#define PH1P35_MCU_QSPI0_DIV                      6
#define PH1P35_MCU_TIMER_CLOCK            100000000


/* default value to freq start */
/* default value to freq end*/

#ifndef PH1P35_MCU_AHB_DIV
#define PH1P35_MCU_AHB_DIV                        4
#endif
#ifndef PH1P35_MCU_QSPI1_DIV
#define PH1P35_MCU_QSPI1_DIV                      6
#endif

#define PH1P35_MCU_USART_CLOCK PH1P35_MCU_CORE_CLOCK
#define PH1P35_MCU_DMA_CLOCK  PH1P35_MCU_CORE_CLOCK
#define PH1P35_MCU_I2C_CLOCK  PH1P35_MCU_CORE_CLOCK
#define PH1P35_MCU_GPIO_CLOCK PH1P35_MCU_CORE_CLOCK

// #define PH1P35_MCU_AHB_ENABLE
#define PH1P35_MCU_APB_ENABLE
#define PH1P35_MCU_GPIO0_ENABLE
#define PH1P35_MCU_GPIO1_ENABLE
#define PH1P35_MCU_GPIO2_ENABLE
#define PH1P35_MCU_GPIO3_ENABLE
#define PH1P35_MCU_GPIO4_ENABLE
#define PH1P35_MCU_GPIO5_ENABLE
#define PH1P35_MCU_GPIO6_ENABLE
#define PH1P35_MCU_GPIO7_ENABLE
// #define PH1P35_MCU_I2C_ENABLE
#define PH1P35_MCU_JTAG_ENABLE
#define PH1P35_MCU_JTAG_SEL                       0
#define PH1P35_MCU_RESET_VECTOR          0x20E00000
// #define PH1P35_MCU_QSPI_ENABLE
// #define PH1P35_MCU_UART0_ENABLE
#define PH1P35_MCU_UART1_ENABLE
#define PH1P35_MCU_UART1_BAUDRATE            115200


/* default value to subip start */
/* default value to subip end*/


/* default value to DDr Controller params start */
/* default value to DDr Controller params end*/



#ifndef PH1P35_MCU_UART0_BAUDRATE
#define PH1P35_MCU_UART0_BAUDRATE             115200
#endif
#ifndef PH1P35_MCU_UART1_BAUDRATE
#define PH1P35_MCU_UART1_BAUDRATE             115200
#endif
/* PL AXI IP instance start, generated by HPF automatically */
#define AL_AXI_DMA_NUM_INSTANCE                0
#define AL_AXI_ETH_LITE_NUM_INSTANCE           0
#define AL_AXI_GPIO_NUM_INSTANCE               0
#define AL_AXI_IIC_NUM_INSTANCE                0
#define AL_AXI_QSPI_NUM_INSTANCE               0
#define AL_AXI_SOFT_NPU_NUM_INSTANCE           0
#define AL_AXI_UART_LITE_NUM_INSTANCE          0
#define AL_AXI_VDMA_NUM_INSTANCE               0
/* PL AXI IP instance end, generated by HPF automatically */

#ifdef __cplusplus
}
#endif
#endif /* __SOC_PLAT_H */
